stop specifying deleteMfa body and header params
openziti/edge-api pull request #12
Opened 2023-03-28 16:54 UTC by qrkourier

closes #11

2023-03-28 17:23 UTC, plorenz requested changes
Change needs to be made in `source/shared/current-identity-mfa.yml` and then the source should be regenerated.

2023-03-28 17:32 UTC, qrkourier commented
@plorenz I see. This hunk of the spec is organized under "shared," and that's why the client-only params are present in the management spec. I'll rewrite the associated issue to reflect this, and so we can discuss the best solution, if any.

2023-03-28 17:35 UTC, andrewpmartinez commented on management.yml
> -      - type: string
The header value is required to remove MFA from the current identity. The body was optional, and technically against the HTTP spec, and can be removed. However the header must stay.

2023-03-28 18:38 UTC, qrkourier commented
> Change needs to be made in `source/shared/current-identity-mfa.yml` and then the source should be regenerated.

I'm troubleshooting a problem with `go-swagger` invoked by `generate_rest.sh`.

```bash
❯ bash -ex ./scripts/generate_rest.sh                                                                                                                                                                                                                                    
+ command -v swagger                                                                                                                                                                                                                                                     
++ realpath ./scripts/generate_rest.sh                                                                                                                                                                                                                                   
+ scriptPath=/home/kbingham/Sites/netfoundry/github/edge-api/scripts/generate_rest.sh                                                                                                                                                                                    
++ dirname /home/kbingham/Sites/netfoundry/github/edge-api/scripts/generate_rest.sh                                                                                                                                                                                      
+ scriptDir=/home/kbingham/Sites/netfoundry/github/edge-api/scripts                                                                                                                                                                                                      
++ realpath /home/kbingham/Sites/netfoundry/github/edge-api/scripts/..                                                                                                                                                                                                   
+ rootDir=/home/kbingham/Sites/netfoundry/github/edge-api                                                                                                                                                                                                                
++ realpath /home/kbingham/Sites/netfoundry/github/edge-api/source/client.yml                                                                                                                                                                                            
+ clientSourceSpec=/home/kbingham/Sites/netfoundry/github/edge-api/source/client.yml                                                                                                                                                                                     
++ realpath -m /home/kbingham/Sites/netfoundry/github/edge-api/client.yml                                                                                                                                                                                                
+ clientSwagSpec=/home/kbingham/Sites/netfoundry/github/edge-api/client.yml                                                                                                                                                                                              
++ realpath /home/kbingham/Sites/netfoundry/github/edge-api/source/management.yml                                                                                                                                                                                        
+ managementSourceSpec=/home/kbingham/Sites/netfoundry/github/edge-api/source/management.yml                                                                                                                                                                             
++ realpath -m /home/kbingham/Sites/netfoundry/github/edge-api/management.yml                                                       
+ managementSwagSpec=/home/kbingham/Sites/netfoundry/github/edge-api/management.yml                                                 
++ realpath /home/kbingham/Sites/netfoundry/github/edge-api/scripts/template.copyright.txt                                                                                                                                                                               
+ copyrightFile=/home/kbingham/Sites/netfoundry/github/edge-api/scripts/template.copyright.txt                                                                                                                                                                           
+ echo '...flattening client spec'                                
...flattening client spec                                         
+ echo swagger flatten /home/kbingham/Sites/netfoundry/github/edge-api/source/client.yml -o /home/kbingham/Sites/netfoundry/github/edge-api/client.yml --format yaml                                                                                                     
swagger flatten /home/kbingham/Sites/netfoundry/github/edge-api/source/client.yml -o /home/kbingham/Sites/netfoundry/github/edge-api/client.yml --format yaml                                                                                                            
+ swagger flatten /home/kbingham/Sites/netfoundry/github/edge-api/source/client.yml -o /home/kbingham/Sites/netfoundry/github/edge-api/client.yml --format yaml                                                                                                          
2023/03/28 14:36:34 format =  yaml                                
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                 
        panic: runtime error: invalid memory address or nil pointer dereference                                                     
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x74fd71]                                                              

goroutine 1 [running]:                                            
gopkg.in/yaml%2ev3.handleErr(0xc00056b8d0)                        
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d                                                           
panic({0xc78e00, 0x13d1740})                                      
        /opt/hostedtoolcache/go/1.19.1/x64/src/runtime/panic.go:884 +0x212                                                          
gopkg.in/yaml%2ev3.(*encoder).node(0xc000601800?, 0xc00031a000?, {0x0?, 0x0?})                                                      
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:434 +0x31                                                         
gopkg.in/yaml%2ev3.(*encoder).node(0xc000601800, 0xc0002994a0, {0x0, 0x0})                                                          
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5                                                       
gopkg.in/yaml%2ev3.(*encoder).node(0xc000601800, 0xc000299360, {0x0, 0x0})                                                          
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5                                                       
gopkg.in/yaml%2ev3.(*encoder).node(0xc000601800, 0xc000299220, {0x0, 0x0})                                                          
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5                                                       
gopkg.in/yaml%2ev3.(*encoder).node(0xc000601800, 0xc000298960, {0x0, 0x0})                                                          
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5                                                       
gopkg.in/yaml%2ev3.(*encoder).node(0xc000601800, 0xc0000010e0, {0x0, 0x0})       [...]

2023-03-28 18:47 UTC, qrkourier commented
Same issue with `go-swagger` CLI v0.30.4.

```bash
❯ alias swagger='podman run --rm -it  --user $(id -u):$(id -g) -e GOPATH=$(go env GOPATH):/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger:0.30.4'

❯ swagger version                                                                                                                                       
version: v0.30.4
commit: df6da9b77aa9751f06bedb17fcf92b1ab67a7a47
```

2023-03-28 18:49 UTC, qrkourier commented
The YAML in the edited fragment seems to be valid.

```bash
$ yq < source/shared/current-identity-mfa.yml >/dev/null && echo YUMMY      
YUMMY
```

2023-04-05 15:51 UTC, qrkourier commented
I'll re-generate this branch as spec v0.25.12.

2023-04-05 17:15 UTC, andrewpmartinez approved these changes

2023-04-05 17:39 UTC, qrkourier commented
resolve conflicts and chang base to twig this .12 off of the .11 branch

2023-04-05 17:50 UTC, merged