clarify Duration minutes indefinite is 0
openziti/edge-api pull request #125
Opened 2024-08-17 13:56 UTC by qrkourier

2024-08-19 14:14 UTC, andrewpmartinez commented on rest_model/external_jwt_signer_create.go
> +
The version I have is: 
```
> swagger version
version: v0.29.0
commit: 09ae1192ca9a941bbb534aca09e6bdc562c95ef3
```

I see https://github.com/go-swagger/go-swagger/releases/tag/v0.31.0 this too.

2024-08-19 14:19 UTC, qrkourier commented on rest_model/external_jwt_signer_create.go
> +
:point_up_2: correct, I installed the latest stable release with `go install` from that repo.

2024-08-19 14:22 UTC, andrewpmartinez commented on rest_model/external_jwt_signer_create.go
> +
Looking through the files more, I see other changes.

Have you checked out the `ziti` repo and use `go work init; go work use .; go work use ../edge-api;` and run the edge API tests?

2024-08-19 14:23 UTC, andrewpmartinez commented on rest_model/external_jwt_signer_create.go
> +
`go test ./... -tags apitests` I believe is the command in the `ziti` repo.

2024-08-19 14:53 UTC, andrewpmartinez requested changes
Looking for a positive test against the `ziti` repo or generating w/ v0.29.0 (or any other version that doesn't alter every file).

2024-08-19 22:41 UTC, qrkourier commented
> Looking for a positive test against the `ziti` repo or generating w/ v0.29.0 (or any other version that doesn't alter every file).

Tests now pass after re-generating with `swagger` v0.29.0. Spot checks of unexpected differences reveal only a change from single to multi-line comments. I'm unsure what, precisely, is responsible. I'm curious to know if re-generating on this branch with v0.29.0 on your machine reverts to single-line comments, or is the change sticky?

I'm asking because we wouldn't want dueling implementations to flap between single and multi-line in subsequent commits, but if it's sticky to multi-line, then we could leave it this way and move on.

2024-08-21 19:07 UTC, andrewpmartinez commented on scripts/generate_rest.sh
> +#!/usr/bin/env bash
Is there no update for the Powershell version?

2024-08-21 19:08 UTC, andrewpmartinez approved these changes

2024-08-21 19:09 UTC, andrewpmartinez commented on scripts/generate_rest.sh
> +#!/usr/bin/env bash
I've never done it before but: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.4

2024-08-21 19:44 UTC, merged